In [91]:
import pandas as pd

In [92]:
train = pd.read_csv('../data/raw/train.csv')

In [93]:
train.head()

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [94]:
train['catalog_content'][0]

'Item Name: La Victoria Green Taco Sauce Mild, 12 Ounce (Pack of 6)\nValue: 72.0\nUnit: Fl Oz\n'

In [95]:
train['catalog_content'][1]

'Item Name: Salerno Cookies, The Original Butter Cookies, 8 Ounce (Pack of 4)\nBullet Point 1: Original Butter Cookies: Classic butter cookies made with real butter\nBullet Point 2: Variety Pack: Includes 4 boxes with 32 cookies total\nBullet Point 3: Occasion Perfect: Delicious cookies for birthdays, weddings, anniversaries\nBullet Point 4: Shareable Treats: Fun to give and enjoy with friends and family\nBullet Point 5: Salerno Brand: Trusted brand of delicious butter cookies since 1925\nValue: 32.0\nUnit: Ounce\n'

In [96]:
train['catalog_content'][2]

'Item Name: Bear Creek Hearty Soup Bowl, Creamy Chicken with Rice, 1.9 Ounce (Pack of 6)\nBullet Point 1: Loaded with hearty long grain wild rice and vegetables\nBullet Point 2: Full of hearty goodness\nBullet Point 3: Single serve bowls\nBullet Point 4: Easy to prepare mix\nBullet Point 5: 0 grams trans fat\nValue: 11.4\nUnit: Ounce\n'

In [97]:
train['catalog_content'][3]

'Item Name: Judee’s Blue Cheese Powder 11.25 oz - Gluten-Free and Nut-Free - Use in Seasonings and Salad Dressings - Great for Dips, Spreads and Sauces - Made in USA\nBullet Point 1: Add to your favorite appetizers, dips & spreads. Use to season popcorn or warmed pita chips.\nBullet Point 2: Sprinkle over french fries, fried chicken, mashed potatoes, roasted veggies, pasta, and more\nBullet Point 3: Made in a dedicated gluten-free facility and shipped in a standup, resealable pouch to ensure freshness\nBullet Point 4: Ingredients: Blue Cheese (Milk, Salt, Cultures, & Enzymes) and Disodium Phosphate\nBullet Point 5: Since 2009, Judee’s has been dedicated to providing fresh, allergy-conscious ingredients, great for your recipes and even better for your family\nProduct Description: Judees Powdered Blue Cheese cheddar cheese powder is an alternative to mozzarella cheese shredded or american cheese slices deli. Make your own alfredo sauce with heavy cream and black buffalo dip with this powder. It adds extra flavor to salad dressing like ranch dressing and great on pizza dough or cauliflower pasta. Add to macaroni and cheese or popcorn seasoning for more aroma and cheesy feel. Combine with mustard and other ingredients to create your own dressing for buffalo chicken or buffalo wings.\nValue: 11.25\nUnit: Ounce\n'

In [98]:
train['catalog_content'] = train['catalog_content'].str.lower()

In [99]:
train['text_length'] = train['catalog_content'].str.len()

https://habr.com/ru/articles/349860/ - просто регулярка в питоне

https://docs-python.ru/packages/modul-pandas-analiz-dannykh-python/ispolzovanie-reguliarnykh-vyrazhenii/ - регулярка в пандас

In [100]:
import re

In [101]:
# Считаем слова
train['word_count'] = train['catalog_content'].str.count(r'\b\w+\b')

In [102]:
train['word_count'].head()

0     19
1     81
2     61
3    213
4     29
Name: word_count, dtype: int64

In [103]:
# Считаем предложения
train['sentence_count'] = train['catalog_content'].str.count(r'[.!?]+')

In [104]:
train['sentence_count'].head()

0    1
1    1
2    2
3    9
4    5
Name: sentence_count, dtype: int64

In [105]:
# Считаем буллеты
train['bullet_count'] = train['catalog_content'].str.count(r'bullet point\s*\d+:')

In [106]:
train['bullet_count'].head()

0    0
1    5
2    5
3    5
4    0
Name: bullet_count, dtype: int64

In [107]:
# Считаем числа
train['number_count'] = train['catalog_content'].str.count(r'\d+(?:\.\d+)?')

In [108]:
train['number_count'].head()

0     3
1    11
2     9
3     8
4     5
Name: number_count, dtype: int64

In [109]:
# Название товара
train['item_name'] = train['catalog_content'].str.extract(r'item name:\s*(.*?)(?=\nvalue:|\nbullet point|\nunit:|$)')

In [110]:
train['item_name'].head()

0    la victoria green taco sauce mild, 12 ounce (p...
1    salerno cookies, the original butter cookies, ...
2    bear creek hearty soup bowl, creamy chicken wi...
3    judee’s blue cheese powder 11.25 oz - gluten-f...
4    kedem sherry cooking wine, 12.7 ounce - 12 per...
Name: item_name, dtype: object

In [111]:
# Название бренда
train['brand'] = train['item_name'].str.extract(r'([A-Za-z0-9\'&.-]+\s+[A-Za-z0-9\'&.-]+)')

In [112]:
train['brand'].head()

0        la victoria
1    salerno cookies
2         bear creek
3             s blue
4       kedem sherry
Name: brand, dtype: object

In [113]:
# Кол-во слов в названии
train['title_word_count'] = train['item_name'].str.count(r'\b\w+\b')

In [114]:
train['title_length'] = train['item_name'].str.len()

In [115]:
# Страна производства
train['made_in_country'] = train['catalog_content'].str.extract(r'made in\s+([a-z ]{2,30})').fillna('0')

In [116]:
train['made_in_country'].unique()

array(['0', 'usa', 'the usa', 'new york city', 'the usa with ',
       'a traditional way', 'germany', 'texas with the finest ingredie',
       'a certified gluten', 'usa ', 'the u', 'a peanut free factory',
       'japan', 'italy', 'candy heaven', 'tucson',
       'small batches to ensure except', 'heaven that will satisfy your ',
       'the usa ', 'australia using over ', 'the usa non', 'france',
       'small batches using only premi', 'finland', 'a gmp', 'just ',
       'a facility that processes othe', 'the usa at sqf iii',
       'puerto rico by holsum', 'canada', 'our allergen', 'america',
       'a zero', 'certified peanut', 'the usa order from the factory',
       'the usa in fda registered faci', 'a ', 'the usa or imported',
       'nut', 'the usa gluten free no sulfur ',
       'the usa with the highest quali', 'facilities that process tree n',
       'a dedicated gluten', 'jerusalem',
       'the usa with absolutely no add', 'small batches', 'gridley',
       'and with ingredients of modena', 'a nut free factory', 'a peanut',
       'facilities free of peanuts', 'italy from sicilian lemons mak',
       'a facility that doesn', 'the usa with real honey ',
       'small batches to preserve prem', 'the ozark mountains in northwe',
       'idaho', 'small hand crafted batches wit',
       'a facility that also processes', 'italy ',
       'the usa so you know it', 'the united states',
       'the usa with flavor crafted wi', 'heaven', 'south korea',
       'sicily', 'west virginia', 'nebraska',
       'the usa with global ingredient', 'united states',
       'usa triple cleaned', 'a nut', 'the usa with care and quality',
       'a peanut and tree nut free fac', 'a animal',
       'our plant that does not proces', 'the usa and gluten free',
       'scotland', 'spain', 'the usa and shipped to you fre',
       'united states of america', 'small batches in our own candy',
       'a facility that does not proce', 'the usa certified kosher ou pa',
       'france of celluloid acetate in', 'nature organic dried apricot',
       'india ', 'thailand', 'allergen', 'canada by kraft food', 'india',
       'a peanut and tree nut', 'the usa in our own sustainably',
       'a peanut free and tree nut fre', 'a peanut and nut free facility',
       'a gmp compliant', 'mexico', 'hawaii ',
       'the usa high quality beef stic', 'vancouver british columbia can',
       'usa pack of ', 'texas', 'the usa great for pizza sandwi',
       'africa hot sauces and spices t', 'switzerland', 'alaska',
       'mexico ', 'wisconsin', 'small batches with ',
       'usa with domestic and imported', 'a way that allows everyone to ',
       'usa at our factory in the foot', 'the netherlands and enjoy its ',
       'tiptree', 'small batches with high', 'hawaii',
       'small batches by hand', 'a facility that follows string',
       'new york', 'belgium', 'the restaurant',
       'a facility that processes tree', 'canada ', 'the us ',
       'a facility that processes whea', 'a dedicated peanut', 'morocco',
       'southern california', 'the usa using a classic formul', 'brazil',
       'cocktail heaven', 'leed certified bakeries that u', 'a new bite',
       'the heart of amish country', 'a gluten free processing facil',
       'a dedicated nut', 'the usa by america',
       'the usa shipped to you fresh', 'a dedicated allergen free faci',
       'the usa using only ', 'the usa using safe',
       'a bakery dedicated to allergen', 'ohio', 'beaune',
       'san francisco', 'a completely wheat free facili',
       'the usa with pure and clean in', 'china', 'new orleans',
       'a gluten', 'house with love and expertise',
       'small batches using a temperat', 'israel',
       'factory that manufactures prod', 'small batches ',
       'a portable and easy', 'the usa from the award winning',
       'this video', 'southern californiattb approve',
       'chicago with mexican tradition', 'your own kitchen', 'erding',
       'usa for fuss', 'south carolina', 'the usa with high quality ingr',
       'ohioingredients', 'oregon', 'the usa while others opt for c',
       'small batchs', 'nature organic plums', 'small batches from high',
       'korea ', 'peanut', 'the united states ', 'small batches and hand',
       'canada by canada dry', 'america ', 'san antonio',
       'our own sustainably operated', 'korea',
       'the usa perfect for pizza or s', 'usa great coffee starts with g',
       'the usa with globally sourced ', 'the',
       'hundreds of different ways', 'small batches and never mass',
       'peru', 'small batches using premium na', 'the usa with the world',
       'australia satisfy that sweet t', 'small batches at ',
       'germany product ', 'lancaster county',
       'usa by wholesome provisions', 'the usa high quality jerky con',
       'tijuana', 'small batches in our historic ', 'snacking heaven',
       'the usa product', 'the usa and certified kosher',
       'the usa in a batch process', 'usa for homemade yogurt', 'crete',
       'ohio and packed into two ', 'new zealand',
       'the usa with fine belgian choc', 'canada at arva flour mills ',
       'halal and kosher certified fac', 'nature organic dried fruit',
       'the mexico', 'the usa to the highest standar', 'ukraine ',
       'germany by august storck ug', 'a gmp facility',
       'a dedicated allergy friendly m', 'modena', 'jamaica',
       'italy bringing the rich', 'texas ', 'north carolina',
       'small batches by the conte fam', 'the philippines by the largest',
       'abruzzo', 'turkey', 'our own manufacturing facility',
       'the usa in a dedicated gluten', 'the usa with quality imported ',
       'north america', 'a tree nut free facility',
       'the usa with whole food ingred', 'a kosher certified facility fo',
       'tea manufacturing facilities t', 'taiwan',
       'small batches with only the fr', 'australia', 'utah',
       'an allergen', 'japan premium peach oolong tea',
       'america and are a celebration ', 'the usa by the award winning s',
       'the usa with high', 'the first brand from chile spe', 'an easy',
       'nature organic dried deglet no', 'france using traditional slow',
       'a peanut ', 'small batches and bottled in f', 'our family',
       'the usa in our eco', 'the japanese sencha style',
       'japan using state', 'a dedicated facility free from',
       'no time at all without artific', 'the usa order from factory dir',
       'the heart of the usa', 'france using traditional metho',
       'korea with fresh ingredients', 'venezuela',
       'india hundreds of years ago', 'small batches to ensure higher',
       'smaller batches for superior t', 'usa by milkylicious', 'holland',
       'italy by italians', 'italy by gerrit j verburg',
       'the usa from domestic and impo', 'america since ', 'pittsburgh',
       'the usa using only usa grown p', 'a dedicated allergen',
       'usa with habanero ', 'poland', 'nebraska ',
       'the usa with one ingredient or', 'france ', 'brittany', 'europe',
       'an sqf', 'the usa using high', 'a nut free facility',
       'pennsylvania using only us', 'pennsylvania',
       'usa garlic granules', 'small batches using time',
       'our bakery in colorado and are', 'puerto rico',
       'belgium in a nut free facility', 'the netherlands', 'japan ',
       'the traditional ways like in t', 'the usa and third',
       'nature are a bit smaller', 'us', 'puerto rico ',
       'a certified organic and gluten', 'a facility that processes cash',
       'nantes', 'a kosher facility following st',
       'small batches with stone groun', 'livermore',
       'a dedicated facility that does', 'fullerton', 'vermont',
       'kosher dairy', 'argentina', 'new england by new englanders',
       'small batches and are certifie', 'canada from domestic and impor',
       'puerto rico and proudly boricu', 'austria',
       'a gmp certified facility', 'kagoshima ',
       'canada with domestic and impor', 'brooklyn ',
       'the usa with north american in', 'an sqf certified facility in r',
       'nature organic dried apricots', 'italy with calabrian chili pep',
       'a dedicated environment for co', 'italy with balsamic vinegar of',
       'the usa with authentic america', 'small batches and crafted with',
       'mexico but a favorite of kids ', 'usa our instant fortified milk',
       'colorado from premium coconut ', 'napa',
       'chicago by a chicagoan shelf l', 'the classic french tradition',
       'jalisco', 'devon england', 'italy safety valve for maximum',
       'a ripe watermelon flavor', 'small batches to ensure qualit',
       'a gluten free facility', 'ireland', 'iso',
       'small batches to ensure optimu', 'the usa by whimsical practical',
       'california ', 'the usa of premium clay source',
       'a dedicated gluten free facili', 'italy since ',
       'a facility free of the top ', 'a dedicated allergy',
       'usa and use non', 'nature organic sun',
       'the usa using thoughtfully sou', 'the usa flavors are more than ',
       'half the time', 'traditional korean fermentatio',
       'the state of washington', 'a family owned business in cen',
       'the united states with premium', 'italy limited edition',
       'italy from durum wheat semolin', 'collaboration with d',
       'costa rica ', 'italy with type ',
       'the usa with premium ingredien', 'small town usa ',
       'the usa using carefully source', 'iowa',
       'a facility that uses eggs and ', 'paradise heaven', 'california',
       'usa good to', 'this website have not been eva',
       'essentially the same way', 'usa with the finest sesame see',
       'bulgaria', 'small batches with gluten free',
       'the same french village as the', 'the usa using only all',
       'small batches with over ', 'nature organic deglet noor dat',
       'the usa perfect with meats', 'traverse city michigan',
       'old fashioned brick ovens', 'france to ensure you get the b',
       'france by an old recipe', 'ashland',
       'a certified zero waste bakery ', 'mankato',
       'a peanut free bakery', 'small batches to ensure freshn',
       'a separate mrs', 'a factory that uses wheat and ',
       'america using only the highest', 'america by a women',
       'louisiana since ', 'greece', 'our state',
       'small batches using time honor', 'small batches for the highest ',
       'pure olive oil', 'nature tart cherry figgy pops',
       'italy high in proteing ', 'british columbia canada', 'australia ',
       'the usa with no soy', 'small batches in the mountains',
       'the usa at our own sqf', 'small batches to ensure the hi',
       'detroit', 'a time when foods were cooked ', 'south africa',
       'boulder', 'small batches using artisan ca', 'vermont for over ',
       'new mexico with flame green ro', 'japan premium jasmine tea',
       'the same bakery as our world f', 'croatia',
       'the holy land of israel', 'europe with the finest ingredi',
       'small batches for quality and ', 'heaven ',
       'a facility that uses eggs', 'your tassimo brewing system in',
       'small batches to bring you gou', 'the usa in quality',
       'small batches with the finest ', 'the us',
       'a separate facility that also ', 'new orleans since ',
       'the usa with locally sourced', 'high heat wood fired',
       'the usa and kosher certified', 'taiwan li hing mui powder is m',
       'the traditional method of care', 'miami ',
       'italy can be used in classic i', 'the top so you can insert a st',
       'partnership with ethical beeke', 'small batches to ensure every ',
       'the usa by betel natural', 'england', 'sweet',
       'usa with pure wild blueberry a', 'the usa without gmos',
       'the usa oat bar bite is perfec', 'the heart of orchard country f',
       'a lab or anything artificial', 'china blue dragon cantonese me',
       'bangalore', 'a peanut free facility',
       'britain and famous on social m', 'a flash and gives you ',
       'the usa from responsibly', 'greece ',
       'nature organic puffed fruit', 'the usa with pride',
       'the usa with us', 'europe ', 'the great pacific northwest si',
       'small batches with great care ', 'snack heaven', 'hong kong',
       'the usa and crafted with real ', 'germany product', 'usa of u',
       'japan in a peanut', 'america by eat play happy',
       'germany and imported fresh in ', 'americas', 'factories',
       'both the usa and south africa ', 'the usa with non', 'maine',
       'brooklyn in small batches and ', 'a certified zero waste facilit',
       'hawai', 'hawaii with ', 'modena and reggio emilia aera',
       'nature organic bananas slices', 'the cleanest',
       'small batches to make a big di', 'the usa using only grown peanu',
       'small batches with real tea an', 'the usa in a gmp',
       'italy soft lady fingers captur', 'the swiss colony bakery',
       'the uk', 'the usa from a secret blend of',
       'small batches with organic mon', 'glass bottles',
       'our factory in brooklyn', 'small batches with all', 'chile',
       'smaller batches', 'belgium and enjoyed as the per',
       'small batches with meticulous ', 'the usa with natural and artif',
       'a dedicated grain free and glu', 'the usa with precision',
       'small batches using premium in', 'the usa using only the finest ',
       'a certified nut free', 'the usa in an fda registered f',
       'a kosher certified facility', 'minutes in the microwave',
       'minutes soup mix', 'a facility powered by the wind', 'gragnano',
       'da bronx', 'california by weibel vineyards',
       'germany and melt in your mouth', 'germany net wt', 'japan in ',
       'the usa using grass', 'small batches onsite at our or',
       'the usa shlef life', 'utah with the highest standard',
       'the usa with mostly local ingr', 'small batches with fair trade ',
       'small batches by arnold', 'compliance with the ',
       'the usa with solid strips of l', 'pakistan', 'our gmp',
       'collaboration with our friends', 'the usa bighorn meals are made',
       'the johnny', 'the ', 'accordance to ancient shamanic',
       'marblehead', 'the usa and grown by farmer bo',
       'the usa with honey from the us', 'montana ',
       'a peanut and gluten free facil', 'the usa flavors that perfectly',
       'tuscany ', 'the philippines', 'a gfco certified facility and ',
       'taiwan ', 'a warehouse that is exposed to',
       'small batches and contains who', 'small batches in the usa with ',
       'a delightful cocktail and we h', 'a peanut free facility so that',
       'the netherlands with historic ', 'a factory that handles nuts',
       'minutes', 'small batches to retain nutrie',
       'usa old fashioned sanded butte', 'a cup while you', 'michigan ',
       'new iberia', 'germany ', 'small batches by local amish f',
       'a premium peanut oil blend for', 'japan of u',
       'the united kingdom', 'puerto rico by cortes hermanos',
       'the usa and are kosher', 'minutes thai wai coconut curry',
       'the usa our freeze dried food ', 'new orleans with fresh high',
       'the heartland of the usa', 'california in small batches to',
       'a facility that is ', 'small batches to ensure great ',
       'dedicated gluten', 'small', 'the whirley pop stovetop popco',
       'the usa in our gfco and ou', 'the usa with our family',
       'the usa to ensure premium qual', 'a dedicated top ',
       'a kitchen that processes nuts', 'three tasty flavors ', 'york',
       'nut free facility', 'the usa and ', 'a mug',
       'our own peanut free facility l', 'italy and imported',
       'americathese chopped vanilla c', 'the usa with real spices for r',
       'homes during all festivals', 'the usa since ', 'turkey ',
       'small batches for a quality ho', 'turkiye', 'england since ',
       'sunny southern california', 'a dedicated nut and gluten fre',
       'africa', 'fiji', 'belgium nut free facility',
       'small batches using only the b', 'the usa using a ',
       'australia by peaceworks', 'ottogi',
       'our usa facility with usa chic', 'heaven when combined with choc',
       'nature fudge brownie minis', 'a certified nut free and glute',
       'the southern provinces of the ', 'sri lanka',
       'the usa and are an ideal keto ', 'orlando', 'israel ', 'vietnam',
       'small batches so that each nug', 'new orleans ',
       'nature organic puffed veg medl', 'the harry ', 'our bakery',
       'the usa with solar energy', 'italy with wheat germ ',
       'italy with over ', 'the traditional european style',
       'a facility that may also proce', 'small batches with the highest',
       'washington', 'malaysia ', 'nature ', 'state',
       'small batches with real candie', 'the usa in a peanut',
       'small batches and flash', 'nature organic dried turkish s',
       'italy in an egg and nut free f', 'the usa from austrailian macad',
       'small batch kitchens artisan c', 'a facility that processes pean',
       'rhode island', 'a labor', 'texas and aged a full ',
       'hawaii since ', 'the usa by q mixers', 'venezuela ',
       'brew heaven', 'the usa from globally sourced ', 'naples italy',
       'small batches by an all', 'the usa from the freshest garl',
       'the usa and is the ', 'the usa using only us',
       'an allergen free facility', 'the usa and shipped to your fr',
       'england all natural gluten fre', 'thailand with high',
       'several ways in india', 'birmingham', 'the level of protien',
       'small batches to ensure the ut', 'mexico but are now a favorite ',
       'usa from imported ingredients', 'heaven and the addition of lem',
       'small batch inother to maintai', 'as little as ',
       'nature apricots ', 'a facility where no peanuts',
       'north america ', 'chicago by a chicagoan', 'brooklyn',
       'nature organic dried cranberri', 'the form of granules',
       'nature organic dried mangoes', 'malmo',
       'india in accordance with holy ', 'and with ingredients from mode',
       'denmark ', 'small batches and packed and c',
       'the finest kc traditions jack ', 'the south',
       'the cooking process', 'eden prairie',
       'gujarati style by deep frying ', 'calabria',
       'the usa and is suitable for ve', 'nut and tree nut free facility',
       'italy gift set ', 'canada with ingredients that a',
       'the usa by an awarded family b', 'poland and loved in america',
       'the scottish highlands', 'liguria',
       'italy making it a premium juic', 'small batches in usa ',
       'colorado', 'the usa by spangler candy comp',
       'usa by sprinkle pop', 'small batches to keep it delic',
       'america by a certified veteran', 'kyoto in small batches by mast',
       'misiones', 'ohio by amish communities', 'dutchess county',
       'our dedicated gluten free faci', 'indonesia', 'kurashiki',
       'sri lanka from high', 'the usa and repacked from bulk',
       'the usa by a trusted brand', 'the united kingdom may contain',
       'a facility that processes soy', 'the usa from u', 'a top ',
       'fawdon', 'kansas city', 'a dedicated nut free ',
       'nature organic superberry frui', 'a pressure cooker without laye',
       'the usa discover the potential', 'the usa and freshly packed wit',
       'the apalachicola river basin i', 'usa with habanero peppers',
       'small batches to ensure superi', 'mexico medium',
       'copper pans in small batches', 'nature organic puffed fruit me',
       'scotland and are a delicious t', 'buffalo', 'holland ',
       'a long time', 'cambridge and has a wonderful ',
       'usa cast iron seasoning and co', 'the philippines by a leading p',
       'the usa by a gmp compliant fac', 'nc', 'portugal', 'nature',
       'sweden', 'south africa ', 'the usa by a family owned comp'],
      dtype=object)

In [117]:
# Флаги стран
train['made_in_usa'] = train['made_in_country'].str.contains(r'\b(?:usa|us|united states|united states of america|america)\b').astype(int)
train['made_in_canada'] = train['made_in_country'].str.contains(r'\bcanada\b').astype(int)
train['made_in_india'] = train['made_in_country'].str.contains(r'\bindia\b').astype(int)
train['made_in_italy'] = train['made_in_country'].str.contains(r'\bitaly\b').astype(int)
train['made_in_canada'] = train['made_in_country'].str.contains(r'\bcanada\b').astype(int)
train['made_in_mexico'] = train['made_in_country'].str.contains(r'\bmexico\b').astype(int)
train['made_in_china'] = train['made_in_country'].str.contains(r'\bchina\b').astype(int)
train['made_in_turkey'] = train['made_in_country'].str.contains(r'\bturkey\b').astype(int)
train['made_in_japan'] = train['made_in_country'].str.contains(r'\bjapan\b').astype(int)
train['made_in_chile'] = train['made_in_country'].str.contains(r'\bchile\b').astype(int)
train['made_in_france'] = train['made_in_country'].str.contains(r'\bfrance\b').astype(int)
train['made_in_spain'] = train['made_in_country'].str.contains(r'\bspain\b').astype(int)
train['made_in_thailand'] = train['made_in_country'].str.contains(r'\bthailand\b').astype(int)
train['made_in_germany'] = train['made_in_country'].str.contains(r'\bgermany\b').astype(int)
train['made_in_england'] = train['made_in_country'].str.contains(r'\bengland\b').astype(int)
train['made_in_sri_lanka'] = train['made_in_country'].str.contains(r'\bsri lanka\b').astype(int)
train['made_in_indonesia'] = train['made_in_country'].str.contains(r'\bindonesia\b').astype(int)
train['made_in_australia'] = train['made_in_country'].str.contains(r'\baustralia\b').astype(int)
train['made_in_new_zealand'] = train['made_in_country'].str.contains(r'\bnew zealand\b').astype(int)

In [118]:
train.columns

Index(['sample_id', 'catalog_content', 'image_link', 'price', 'text_length',
       'word_count', 'sentence_count', 'bullet_count', 'number_count',
       'item_name', 'brand', 'title_word_count', 'title_length',
       'made_in_country', 'made_in_usa', 'made_in_canada', 'made_in_india',
       'made_in_italy', 'made_in_mexico', 'made_in_china', 'made_in_turkey',
       'made_in_japan', 'made_in_chile', 'made_in_france', 'made_in_spain',
       'made_in_thailand', 'made_in_germany', 'made_in_england',
       'made_in_sri_lanka', 'made_in_indonesia', 'made_in_australia',
       'made_in_new_zealand'],
      dtype='object')

In [119]:
# Единица измерения
train['unit'] = train['catalog_content'].str.extract(r'unit:\s*([A-Za-z\- ]+)')

In [120]:
# Наличие упаковки
train['has_pack'] = train['catalog_content'].str.contains(r'\bpack\b').astype(int)

In [121]:
# Количество упаковок
train['pack_quantity'] = train['catalog_content'].str.extract(r'pack\s*of\s*(\d+)')

In [122]:
train['pack_quantity'] = train['pack_quantity'].fillna(1).astype('int')

In [123]:
train['pack_quantity'].unique()

array([   6,    4,    1,    2,   12,    5,    3,    8,   50,   24,    9,
         20,  100,    7,  500,   14,   32,   18,   36,   25,   10,   64,
         15,   22,   16,  192,   40,   11,   48,   60,   30,  101,   85,
         19,   90,   96,   70,   28, 2424,  200,   21,  250,   80,  108,
        120,   34,   72,   88,   42,   35, 2000,   66,  150,  144,   17,
          0,   55,   45,   27,  180,  104,   84,  360,   54,  160,   23,
       1000,   29,  300,   65,  600,  102,   13,  185, 1212,   44,  416,
         26,  750,  297,  216,   56,  450,   46,  400,  128,  240,  126,
         52,   76,  288,  210,   78, 1200,   68,  350,   95])

In [124]:
train['has_pack'].value_counts()

has_pack
0    43227
1    31773
Name: count, dtype: int64

In [125]:
# Наличие состава
train['has_ingredients'] = train['catalog_content'].str.contains(r'\bingredients?\b').astype(int)

In [126]:
train['has_ingredients'].value_counts()

has_ingredients
0    54324
1    20676
Name: count, dtype: int64

In [127]:
# Диетические признаки
train['organic'] = train['catalog_content'].str.contains(r'\borganic\b').astype(int)
train['gluten_free'] = train['catalog_content'].str.contains(r'gluten[\s-]*free').astype(int)
train['vegan'] = train['catalog_content'].str.contains(r'\bvegan\b').astype(int)
train['protein'] = train['catalog_content'].str.contains(r'\bprotein\b').astype(int)
train['sugar_free'] = train['catalog_content'].str.contains(r'sugar[\s-]*free').astype(int)
train['nut_free'] = train['catalog_content'].str.contains(r'nut[\s-]*free').astype(int)
train["dairy_free"] = train["catalog_content"].str.contains(r"dairy[\s-]*free").astype(int)
train["soy_free"] = train["catalog_content"].str.contains(r"soy[\s-]*free").astype(int)
train["keto"] = train["catalog_content"].str.contains(r"\bketo\b").astype(int)
train["kosher"] = train["catalog_content"].str.contains(r"\bkosher\b").astype(int)
train["halal"] = train["catalog_content"].str.contains(r"\bhalal\b").astype(int)

In [128]:
train['dairy_free'].value_counts()

dairy_free
0    72910
1     2090
Name: count, dtype: int64

In [129]:
train['soy_free'].value_counts()

soy_free
0    74002
1      998
Name: count, dtype: int64

In [130]:
train['halal'].value_counts()

halal
0    74371
1      629
Name: count, dtype: int64

In [131]:
train['keto'].value_counts()

keto
0    71732
1     3268
Name: count, dtype: int64

In [132]:
train['kosher'].value_counts()

kosher
0    61845
1    13155
Name: count, dtype: int64

In [133]:
train['nut_free'].value_counts()

nut_free
0    73450
1     1550
Name: count, dtype: int64

In [134]:
train['sugar_free'].value_counts()

sugar_free
0    72057
1     2943
Name: count, dtype: int64

In [135]:
train['organic'].value_counts()

organic
0    65247
1     9753
Name: count, dtype: int64

In [136]:
train['gluten_free'].value_counts()

gluten_free
0    60770
1    14230
Name: count, dtype: int64

In [137]:
train['vegan'].value_counts()

vegan
0    66730
1     8270
Name: count, dtype: int64

In [138]:
train['protein'].value_counts()

protein
0    68922
1     6078
Name: count, dtype: int64

In [139]:
(train['brand'].value_counts()/len(train['brand'].unique())).head()

brand
food to            0.035485
betty crocker      0.011253
bob's red          0.010090
amoretti -         0.008665
marshalls creek    0.008590
Name: count, dtype: float64

In [140]:
brand_frequency_dict = dict(train['brand'].value_counts()/len(train['brand'].unique()))

In [141]:
train['brand_frequency'] = train['brand'].replace(brand_frequency_dict)

/var/folders/h5/t5dxgffs3r172t83x2g98mv00000gn/T/ipykernel_73479/1361680721.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['brand_frequency'] = train['brand'].replace(brand_frequency_dict)

In [142]:
train[['brand','brand_frequency']].head()

             brand  brand_frequency
0      la victoria         0.001313
1  salerno cookies         0.000038
2       bear creek         0.000713
3           s blue         0.000038
4     kedem sherry         0.000038

In [143]:
brand_frequency_dict['la victoria']

np.float64(0.0013128774522675269)

In [144]:
train.columns

Index(['sample_id', 'catalog_content', 'image_link', 'price', 'text_length',
       'word_count', 'sentence_count', 'bullet_count', 'number_count',
       'item_name', 'brand', 'title_word_count', 'title_length',
       'made_in_country', 'made_in_usa', 'made_in_canada', 'made_in_india',
       'made_in_italy', 'made_in_mexico', 'made_in_china', 'made_in_turkey',
       'made_in_japan', 'made_in_chile', 'made_in_france', 'made_in_spain',
       'made_in_thailand', 'made_in_germany', 'made_in_england',
       'made_in_sri_lanka', 'made_in_indonesia', 'made_in_australia',
       'made_in_new_zealand', 'unit', 'has_pack', 'pack_quantity',
       'has_ingredients', 'organic', 'gluten_free', 'vegan', 'protein',
       'sugar_free', 'nut_free', 'dairy_free', 'soy_free', 'keto', 'kosher',
       'halal', 'brand_frequency'],
      dtype='object')

In [145]:
train['unit'].unique()

array(['fl oz', 'ounce', 'count', 'none', 'fluid ounce', 'oz', 'ounces',
       'pound', 'gram', 'grams', 'lb', 'each', 'liters', 'gramm', 'ct',
       'fl oz ', 'millilitre', 'jar', 'fl', 'bottle', 'can', 'tea bags',
       ' ', 'each ', 'pack', 'piece', 'fluid ounces', 'gr', 'milliliter',
       'mililitro', 'pounds', 'kg', 'bag', 'in', 'ounce ', 'k-cups',
       'sq ft', '-', 'ml', 'packs', 'box', 'fl ounce', 'pouch', 'bucket',
       'per box', 'per package', 'comes as a single ', 'units', 'case',
       'product', 'per carton', 'foot', 'cm', 'unit',
       'paper cupcake liners', 'capsule', 'bottles', '---',
       'ziplock bags', 'ltr', 'carton'], dtype=object)

In [146]:
train['unit'].value_counts()

unit
ounce                 42940
count                 18209
fl oz                 11241
oz                     1064
none                    940
                      ...
comes as a single         1
per package               1
bucket                    1
-                         1
carton                    1
Name: count, Length: 61, dtype: int64

In [147]:
unit_list_before_clean = train['unit'].unique()

In [148]:
unit_dict = {
    'ounce': 'oz',
    'ounces': 'oz',
    'oz': 'oz',
    'gram': 'gr',
    'grams': 'gr',
    'gramm': 'gr',
    'gr': 'gr',
    'g': 'gr',
    'pound': 'lb',
    'pounds': 'lb',
    'lb': 'lb',
    'kg': 'kg',
    'fl oz': 'fl_oz',
    'fl oz ': 'fl_oz',
    'fluid ounce': 'fl_oz',
    'fluid ounces': 'fl_oz',
    'fl ounce': 'fl_oz',
    'ml': 'ml',
    'milliliter': 'ml',
    'millilitre': 'ml',
    'mililitro': 'ml',
    'liter': 'liter',
    'liters': 'liter',
    'ltr': 'liter',
    'count': 'count',
    'ct': 'count',
    'unit': 'unit',
    'units': 'unit',
    'each': 'unit',
    'piece': 'piece',
    'pack': 'pack',
    'packs': 'pack',
    'box': 'box',
    'per box': 'box',
    'bag': 'bag',
    'bottle': 'bottle',
    'bottles': 'bottle',
    'jar': 'jar',
    'can': 'can',
    'carton': 'carton',
    'per carton': 'carton',
    'case': 'case',
    'bucket': 'bucket',
    'pouch': 'pouch',
    ' ': 'None',
    '-': 'None',
    '---': 'None'
}

In [149]:
train['unit'] = train['unit'].replace(unit_dict)

In [150]:
train['unit'].unique()

array(['fl_oz', 'oz', 'count', 'none', 'lb', 'gr', 'unit', 'liter', 'ml',
       'jar', 'fl', 'bottle', 'can', 'tea bags', 'None', 'each ', 'pack',
       'piece', 'kg', 'bag', 'in', 'ounce ', 'k-cups', 'sq ft', 'box',
       'pouch', 'bucket', 'per package', 'comes as a single ', 'case',
       'product', 'carton', 'foot', 'cm', 'paper cupcake liners',
       'capsule', 'ziplock bags'], dtype=object)

In [151]:
# Объем товара
train['value'] = train['catalog_content'].str.extract(r'value:\s([\d.]+)').astype(float)

In [152]:
train.head()

,sample_id,catalog_content,image_link,price,text_length,word_count,sentence_count,bullet_count,number_count,item_name,...,protein,sugar_free,nut_free,dairy_free,soy_free,keto,kosher,halal,brand_frequency,value
0,33127,"item name: la victoria green taco sauce mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89,91,19,1,0,3,"la victoria green taco sauce mild, 12 ounce (p...",...,0,0,0,0,0,0,0,0,0.001313,72.00
1,198967,"item name: salerno cookies, the original butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12,511,81,1,5,11,"salerno cookies, the original butter cookies, ...",...,0,0,0,0,0,0,0,0,0.000038,32.00
2,261251,"item name: bear creek hearty soup bowl, creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97,328,61,2,5,9,"bear creek hearty soup bowl, creamy chicken wi...",...,0,0,0,0,0,0,0,0,0.000713,11.40
3,55858,item name: judee’s blue cheese powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34,1318,213,9,5,8,judee’s blue cheese powder 11.25 oz - gluten-f...,...,0,0,1,0,0,0,0,0,0.000038,11.25
4,292686,"item name: kedem sherry cooking wine, 12.7 oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49,155,29,5,0,5,"kedem sherry cooking wine, 12.7 ounce - 12 per...",...,0,0,0,0,0,0,0,0,0.000038,12.00

Добавим разделение на категории товаров по тексту

In [153]:
train['is_food'] = train['catalog_content'].str.contains(r'food').astype(int)

In [154]:
train['is_food'].sum()

np.int64(13482)

In [155]:
#напитки
train['is_drink'] = train['catalog_content'].str.contains(r'coffee|tea|cocoa|espresso|drink|juice|beverage').astype(int)

#витамины
train['is_health'] = train['catalog_content'].str.contains(r'protein|vitamin|supplement|whey|collagen|creatine').astype(int)

#средства ухода
train['is_beauty'] = train['catalog_content'].str.contains(r'shampoo|conditioner|soap|cream|lotion|serum').astype(int)

#уход за животными
train['is_pet'] = train['catalog_content'].str.contains(r'dog|cat|pet|puppy|kitten').astype(int)

#уход за детьми
train['is_baby'] = train['catalog_content'].str.contains(r'baby|infant|toddler').astype(int)

#средства для дома
train['is_household'] = train['catalog_content'].str.contains(r'detergent|cleaner|laundry|dishwasher').astype(int)

In [156]:
train['is_household'].value_counts()

is_household
0    74615
1      385
Name: count, dtype: int64

In [157]:
train['is_baby'].value_counts()

is_baby
0    73611
1     1389
Name: count, dtype: int64

In [158]:
train['is_pet'].value_counts()

is_pet
0    65480
1     9520
Name: count, dtype: int64

In [159]:
train['is_beauty'].value_counts()

is_beauty
0    66824
1     8176
Name: count, dtype: int64

In [160]:
train['is_health'].value_counts()

is_health
0    64919
1    10081
Name: count, dtype: int64

In [161]:
train['is_drink'].value_counts()

is_drink
0    50247
1    24753
Name: count, dtype: int64

In [162]:
#премиальность
train["is_premium"] = train["catalog_content"].str.contains(r"premium|gourmet|artisan|imported|authentic|luxury").astype(int)

#натуральность
train["is_natural"] = train["catalog_content"].str.contains(r"natural|pure|non[\s-]*gmo|no preservatives").astype(int)

In [163]:
train['is_premium'].value_counts()

is_premium
0    56340
1    18660
Name: count, dtype: int64

In [164]:
train['is_natural'].value_counts()

is_natural
0    47360
1    27640
Name: count, dtype: int64

In [165]:
train['total_amount'] = train['value'] * train['pack_quantity'].astype(float)

In [166]:
train.to_csv('../data/extracted/train_extracted.csv')